#!/usr/bin/env bash
# Build dram_img.h (DDR image: input + weights + BN + CSR program) and gold.h
# (expected 6-layer output) from the files quant_cnn.py produced.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
PY="$HERE/../../python"
OUT="$HERE/src"

tr -d '\r' < "$PY/dram.txt" | awk '
BEGIN { print "// generated by gen_headers.sh from python/dram.txt";
        print "#ifndef DRAM_IMG_H"; print "#define DRAM_IMG_H"; print "#include <stdint.h>";
        print "#define DRAM_WORDS 65536U"; print "static const uint32_t dram_img[DRAM_WORDS] = {" }
{ printf "0x%su,%s", $1, (NR % 8 == 0 ? "\n" : " ") }
END { print "};"; print "#endif" }' > "$OUT/dram_img.h"

paste -d' ' <(tr -d '\r' < "$PY/gold_addr.txt") <(tr -d '\r' < "$PY/gold.txt") | awk '
BEGIN { print "// generated by gen_headers.sh from python/gold_addr.txt, python/gold.txt";
        print "#ifndef GOLD_H"; print "#define GOLD_H"; print "#include <stdint.h>";
        print "#define GOLD_N 928U" }
{ a[NR] = $1; v[NR] = $2 }
END {
  print "static const uint16_t gold_addr[GOLD_N] = {";
  for (i = 1; i <= NR; i++) printf "0x%su,%s", a[i], (i % 12 == 0 ? "\n" : " ");
  print "};";
  print "static const uint32_t gold_val[GOLD_N] = {";
  for (i = 1; i <= NR; i++) printf "0x%su,%s", v[i], (i % 8 == 0 ? "\n" : " ");
  print "};"; print "#endif" }' > "$OUT/gold.h"

echo "wrote $OUT/dram_img.h and $OUT/gold.h"
